#!/usr/bin/env bash
# Config deployment script
# Usage: ./deploy.sh --env <environment> [--service <service>] [--dry-run]
#
# Validates config for the target environment, then copies the resolved
# config to the appropriate service directory.
#
# Services: indexer, all
# Environments: development, staging, production

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

ENV=""
SERVICE="all"
DRY_RUN=false

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)      ENV="$2";     shift 2 ;;
    --service)  SERVICE="$2"; shift 2 ;;
    --dry-run)  DRY_RUN=true; shift   ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

if [[ -z "$ENV" ]]; then
  echo "Error: --env is required (development|staging|production)"
  exit 1
fi

if [[ ! "$ENV" =~ ^(development|staging|production)$ ]]; then
  echo "Error: unknown environment '$ENV'"
  exit 1
fi

echo "==> Deploying config | env=$ENV service=$SERVICE dry_run=$DRY_RUN"

# ---------------------------------------------------------------------------
# Step 1: Validate
# ---------------------------------------------------------------------------
echo ""
echo "--> Validating config..."
cd "$SCRIPT_DIR"
APP_ENV="$ENV" npx ts-node validate.ts --env "$ENV"

# ---------------------------------------------------------------------------
# Step 2: Deploy to services
# ---------------------------------------------------------------------------
deploy_indexer() {
  local src="$SCRIPT_DIR/environments/${ENV}.toml"
  local base="$SCRIPT_DIR/base.toml"
  local dest="$ROOT_DIR/indexer/config.${ENV}.toml"

  echo ""
  echo "--> Deploying indexer config: $dest"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "    [dry-run] Would copy base.toml + ${ENV}.toml → $dest"
    return
  fi

  # Write a merged header comment then concatenate base + env override
  {
    echo "# Auto-generated by config/deploy.sh — do not edit manually"
    echo "# Environment: $ENV | Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Config version: $(node -e "console.log(require('./versions.json').current)")"
    echo ""
    cat "$base"
    echo ""
    echo "# --- Environment overrides ($ENV) ---"
    cat "$src"
  } > "$dest"

  echo "    Written: $dest"
}

case "$SERVICE" in
  indexer) deploy_indexer ;;
  all)     deploy_indexer ;;
  *)
    echo "Error: unknown service '$SERVICE'. Valid: indexer, all"
    exit 1
    ;;
esac

echo ""
echo "==> Done."
