use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ContractError {
    AlreadyInitialized = 1,
    NotInitialized = 2,
    InvalidAmount = 3,
    InvalidFeeBps = 4,
    Overflow = 5,
    Unauthorized = 6,
    ContractPaused = 7,
    InvalidStatus = 8,
    TradeNotFound = 9,
    ArbitratorNotRegistered = 10,
    KycNotVerified = 11,
    AmlNotCleared = 12,
    JurisdictionRestricted = 13,
    TradeAmountLimitExceeded = 14,
    ComplianceDataMissing = 15,
    NoFeesToWithdraw = 16,
    InvalidMetadata = 17,
    MetadataValueTooLong = 18,
    InvalidExpiry = 19,
    NoArbitrator = 20,
    TradeExpired = 21,
    TradeNotExpired = 22,
    MigrationAlreadyApplied = 23,
    MigrationVersionMismatch = 24,
    BridgeOracleNotSet = 25,
    BridgeTradeExpired = 26,
    BridgeTradeNotExpired = 27,
    InsuranceProviderNotRegistered = 28,
    InsurancePremiumTooHigh = 29,
    TradeNotInsured = 30,
    InsuranceAlreadyClaimed = 31,
    InsuranceClaimNotEligible = 32,
    InvalidSplitBps = 33,
}
