use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ContractError {
    AlreadyInitialized = 1,
    NotInitialized = 2,
    InvalidAmount = 3,
    InvalidFeeBps = 4,
    Overflow = 5,
    Unauthorized = 6,
    ContractPaused = 7,
    InvalidStatus = 8,
    TradeNotFound = 9,
    ArbitratorNotRegistered = 10,
    KycNotVerified = 11,
    AmlNotCleared = 12,
    JurisdictionRestricted = 13,
    TradeAmountLimitExceeded = 14,
    ComplianceDataMissing = 15,
    NoFeesToWithdraw = 16,
    InvalidMetadata = 17,
    MetadataValueTooLong = 18,
    InvalidExpiry = 19,
    NoArbitrator = 20,
    TradeExpired = 21,
    TradeNotExpired = 22,
    MigrationAlreadyApplied = 23,
    MigrationVersionMismatch = 24,
    BridgeOracleNotSet = 25,
    BridgeTradeExpired = 26,
    BridgeTradeNotExpired = 27,
    InsuranceProviderNotRegistered = 28,
    InsurancePremiumTooHigh = 29,
    TradeNotInsured = 30,
    InsuranceAlreadyClaimed = 31,
    InsuranceClaimNotEligible = 32,
    InvalidSplitBps = 33,
    // Metadata errors (duplicates removed)
    InvalidTierConfig = 14,
    TierNotFound = 15,
    TemplateNotFound = 16,
    TemplateInactive = 17,
    TemplateNameTooLong = 18,
    TemplateVersionLimitExceeded = 19,
    TemplateAmountMismatch = 20,
    SubscriptionNotFound = 21,
    SubscriptionExpired = 22,
    SubscriptionAlreadyActive = 23,
    ProposalNotFound = 24,
    ProposalNotActive = 25,
    AlreadyVoted = 26,
    InsufficientVotingPower = 27,
    ProposalNotPassed = 28,
    ProposalAlreadyExecuted = 29,
    VotingEnded = 30,
    PrivacyDataTooLong = 31,
    DisclosureGrantNotFound = 32,
    DisclosureUnauthorized = 33,
    MigrationAlreadyApplied = 21,
    MigrationVersionMismatch = 22,
    BridgeOracleNotSet = 23,
    BridgeTradeExpired = 24,
    BridgeTradeNotExpired = 25,
    InsuranceProviderNotRegistered = 26,
    InsurancePremiumTooHigh = 27,
    TradeNotInsured = 28,
    InsuranceAlreadyClaimed = 29,
    InsuranceClaimNotEligible = 30,
    // Oracle errors (40–44)
    OracleNotFound = 40,
    OracleAlreadyRegistered = 41,
    OracleListFull = 42,
    OracleUnavailable = 43,
    OraclePriceInvalid = 44,
    // AMM errors (50–54)
    AmmPoolNotFound = 50,
    // Bridge errors (80–99)
    BridgeProviderNotFound = 80,
    BridgeProviderAlreadyRegistered = 81,
    BridgeProviderLimitExceeded = 82,
    BridgeTradeNotFound = 83,
    BridgeTradeExpired = 84,
    BridgeTradeNotExpired = 85,
    BridgeRetryLimitExceeded = 86,
    BridgeAttestationInvalid = 87,
    BridgeAttestationExpired = 88,
    BridgeAmountOutOfRange = 89,
    BridgeChainNotSupported = 90,
    BridgeOracleNotAuthorized = 91,
    BridgePaused = 92,
    BridgeSignatureInvalid = 93,
    BridgeNonceAlreadyUsed = 94,
    AmmSlippageExceeded = 51,
    AmmInsufficientShares = 52,
    AmmInvalidPair = 53,
    AmmPoolAlreadyExists = 54,
    // Upgrade system errors (60–66)
    /// An upgrade is already in progress (guard is set).
    UpgradeInProgress = 60,
    /// No upgrade proposal exists to execute or cancel.
    NoUpgradeProposal = 61,
    /// Timelock has not yet expired; upgrade cannot be executed yet.
    UpgradeTimelockActive = 62,
    /// No upgrade guard is set; migrate/rollback called out of sequence.
    NoUpgradeInProgress = 63,
    /// Rollback window has passed; state cannot be reverted automatically.
    RollbackWindowExpired = 64,
    // Multi-sig arbitration errors (70–74)
    /// threshold == 0 or threshold > arbitrators count.
    InvalidMultiSigConfig = 70,
    /// Arbitrator has already cast a vote for this trade.
    AlreadyVoted = 71,
    /// Voting window has expired; no more votes accepted.
    VotingExpired = 72,
    /// Voting window has not yet expired; cannot force-resolve.
    VotingNotExpired = 73,
    /// No consensus reached among arbitrators.
    NoConsensus = 74,
    // Social feature errors (70-74)
    CannotFollowSelf = 70,
    NotFollowing = 71,
    NoTrigger = 113,
    PriceConditionNotMet = 114,
}
